function generateIntro() {
  const podcast = document.getElementById("podcastName").value;
  const episode = document.getElementById("episodeTitle").value;
  const host = document.getElementById("hostName").value;
  const style = document.getElementById("style").value;

  const intros = {
    professional: [
      `Welcome to ${podcast}. I’m ${host}, and today we cover "${episode}".`,
      `Hello listeners! ${host} here on ${podcast} discussing "${episode}".`,
      `Greetings! On ${podcast}, I’m ${host}, bringing insights on "${episode}".`,
      `Hi everyone! I’m ${host}, and today’s episode is about "${episode}".`,
      `Thank you for joining ${podcast}. I’m ${host}, exploring "${episode}".`,
      `Welcome back! ${host} here, guiding you through "${episode}" on ${podcast}.`,
      `Hello and welcome to ${podcast}. I’m ${host}, here to discuss "${episode}".`,
      `Greetings listeners! ${host} on ${podcast} today with "${episode}".`,
      `Hi friends! Today on ${podcast}, we cover "${episode}". I’m ${host}.`,
      `Welcome everyone! I’m ${host}, discussing "${episode}" on ${podcast}.`,
      `Hello! ${host} here on ${podcast}, diving into "${episode}".`,
      `Greetings everyone! On ${podcast}, I’m ${host}, discussing "${episode}".`,
      `Welcome! ${host} here, exploring "${episode}" today on ${podcast}.`,
      `Hi all! This is ${host} on ${podcast}, sharing insights on "${episode}".`,
      `Good day! ${host} here, bringing you the details of "${episode}" on ${podcast}.`,
      `Hello listeners! On ${podcast}, I’m ${host}, focusing on "${episode}".`,
      `Welcome to another episode of ${podcast}. I’m ${host}, here to discuss "${episode}".`,
      `Greetings! ${host} here, bringing clarity on "${episode}" for ${podcast}.`,
      `Hi friends! ${host} on ${podcast} today discussing "${episode}".`,
      `Hello everyone! I’m ${host}, providing insights on "${episode}" on ${podcast}.`,
      `Welcome back! ${host} here to guide you through "${episode}" on ${podcast}.`,
      `Greetings listeners! ${host} on ${podcast} with an in-depth look at "${episode}".`,
      `Hi there! I’m ${host}, and today on ${podcast} we cover "${episode}".`,
      `Hello everyone! ${host} here to bring you expert insights on "${episode}" on ${podcast}.`,
      `Welcome to ${podcast}! I’m ${host}, discussing everything about "${episode}".`,
      `Greetings listeners! ${host} here, exploring the nuances of "${episode}" on ${podcast}.`,
      `Hi all! On ${podcast}, I’m ${host}, diving into the details of "${episode}".`,
      `Hello and welcome! I’m ${host} on ${podcast}, covering the topic "${episode}".`,
      `Welcome friends! ${host} here to break down "${episode}" on ${podcast}.`,
      `Greetings! I’m ${host}, taking you through the key points of "${episode}" on ${podcast}.`
    ],
    humour: [
      `Hey there! ${host} on ${podcast}, talking about "${episode}" — but with laughs!`,
      `Welcome! I’m ${host} on ${podcast}, turning "${episode}" into a comedy show.`,
      `Hi friends! Today on ${podcast}, we laugh while discussing "${episode}".`,
      `Hello everyone! ${host} here on ${podcast}, making "${episode}" fun and silly.`,
      `Greetings listeners! "${episode}" has never been this funny, welcome to ${podcast}.`,
      `Hey! ${host} here, presenting "${episode}" with a humorous twist on ${podcast}.`,
      `Welcome back! Laugh along as we explore "${episode}" on ${podcast}.`,
      `Hi there! ${host} on ${podcast} today, joking about "${episode}".`,
      `Hello! Let’s turn "${episode}" into a comedy moment on ${podcast}.`,
      `Greetings everyone! ${host} here to lighten up "${episode}" on ${podcast}.`,
      `Hey folks! ${podcast} is here with laughs and insights on "${episode}".`,
      `Hi friends! I’m ${host}, making "${episode}" a fun discussion on ${podcast}.`,
      `Hello everyone! Today on ${podcast}, we tackle "${episode}" with humour.`,
      `Welcome back! ${host} on ${podcast}, joking about "${episode}" all the way.`,
      `Greetings! We’re turning "${episode}" into a hilarious ride on ${podcast}.`,
      `Hi all! Laugh and learn with "${episode}" today on ${podcast}.`,
      `Hey there! I’m ${host}, making "${episode}" funny yet informative on ${podcast}.`,
      `Hello! Today on ${podcast}, laughter meets learning with "${episode}".`,
      `Greetings listeners! "${episode}" gets a comedic spin on ${podcast}.`,
      `Hi friends! ${host} here on ${podcast}, bringing humour to "${episode}".`,
      `Welcome! Enjoy jokes and insights on "${episode}" on ${podcast}.`,
      `Hey everyone! ${host} and ${podcast} today, laughing through "${episode}".`,
      `Hello listeners! "${episode}" never felt this fun on ${podcast}.`,
      `Greetings! I’m ${host}, turning "${episode}" into comedy gold on ${podcast}.`,
      `Hi all! ${podcast} brings you laughter with "${episode}".`,
      `Hey there! Let’s giggle and learn about "${episode}" on ${podcast}.`,
      `Welcome back! Humour meets topic on "${episode}" today on ${podcast}.`,
      `Hi friends! Laugh along with ${host} on ${podcast} while covering "${episode}".`,
      `Hello everyone! Today’s "${episode}" gets a funny twist on ${podcast}.`,
      `Greetings listeners! ${host} makes "${episode}" a lighthearted discussion on ${podcast}.`
    ],
    satire: [
      `Welcome! ${host} here on ${podcast}, poking fun at "${episode}".`,
      `Hello listeners! Today’s satirical take on "${episode}" is brought to you by ${podcast}.`,
      `Hi everyone! ${host} on ${podcast}, twisting "${episode}" with satire.`,
      `Greetings! "${episode}" gets a witty spin on ${podcast}.`,
      `Hey friends! Satire meets insights today on "${episode}" at ${podcast}.`,
      `Welcome back! ${host} delivers irony with "${episode}" on ${podcast}.`,
      `Hello! ${podcast} presents "${episode}" with a satirical angle.`,
      `Hi listeners! Laugh at the absurdities of "${episode}" on ${podcast}.`,
      `Greetings! ${host} critiques "${episode}" with humour and irony on ${podcast}.`,
      `Hey everyone! Today’s ${podcast} episode offers satire on "${episode}".`,
      `Welcome! ${host} here, presenting "${episode}" with a clever twist on ${podcast}.`,
      `Hello friends! ${podcast} brings satire to the topic "${episode}".`,
      `Greetings listeners! Let’s poke fun at "${episode}" on ${podcast}.`,
      `Hi all! Satirical insights into "${episode}" today on ${podcast}.`,
      `Hey there! ${host} spins "${episode}" with irony on ${podcast}.`,
      `Hello! Enjoy a witty look at "${episode}" on ${podcast}.`,
      `Greetings! ${podcast} gives a humorous critique of "${episode}".`,
      `Hi friends! Today’s "${episode}" has a satirical twist on ${podcast}.`,
      `Welcome! ${host} explores "${episode}" with irony on ${podcast}.`,
      `Hey listeners! Satire meets topic in "${episode}" on ${podcast}.`,
      `Hello everyone! A clever take on "${episode}" today on ${podcast}.`,
      `Greetings! ${host} delivers a witty commentary on "${episode}" on ${podcast}.`,
      `Hi all! Enjoy a satirical ride through "${episode}" on ${podcast}.`,
      `Hey friends! "${episode}" gets a humorous twist on ${podcast}.`,
      `Hello! ${host} makes "${episode}" funnier on ${podcast}.`,
      `Greetings listeners! Satire rules today in "${episode}" on ${podcast}.`,
      `Hi everyone! ${host} presents "${episode}" with wit on ${podcast}.`,
      `Hey there! Let’s laugh and think about "${episode}" on ${podcast}.`,
      `Welcome back! Satirical insights on "${episode}" by ${host} on ${podcast}.`,
      `Hi friends! Enjoy irony and humour in "${episode}" on ${podcast}.`
    ],
    horror: [
    `Welcome brave souls! I’m ${host}, and tonight on ${podcast} we face the chilling "${episode}".`,
  `Dare to listen? ${podcast} with ${host} brings "${episode}" into the darkness.`,
  `Greetings, fear seekers! ${host} here on ${podcast} exploring the horror of "${episode}".`,
  `Enter if you dare: ${podcast} presents "${episode}" with your host, ${host}.`,
  `Hello, creatures of the night! ${host} here to unravel "${episode}" on ${podcast}.`,
  `Tonight on ${podcast}, ${host} delves into the terrifying "${episode}".`,
  `Welcome to ${podcast}, the place where "${episode}" haunts us. I’m ${host}.`,
  `Prepare for unease on ${podcast} with ${host} as we discuss "${episode}".`,
  `Hello, and beware! ${host} here on ${podcast} with "${episode}".`,
  `Darkness falls as ${podcast} and ${host} bring you "${episode}".`,
  `Step into the shadows with ${host} on ${podcast} exploring "${episode}".`,
  `Fear lurks on ${podcast} tonight with ${host} and the topic "${episode}".`,
  `Welcome, mortals! ${host} here to dissect the horrors of "${episode}" on ${podcast}.`,
  `Listen close... ${host} brings you "${episode}" on ${podcast}.`,
  `Ghouls and ghosts await you on ${podcast} with ${host} covering "${episode}".`,
  `${podcast} invites you to face fear with ${host} discussing "${episode}".`,
  `Welcome night dwellers! ${host} here on ${podcast} for "${episode}".`,
  `Brace yourself as ${host} explores "${episode}" on ${podcast}.`,
  `${podcast} presents ${host} unraveling the mystery of "${episode}".`,
  `Tonight we confront the unknown in ${episode} with ${host} on ${podcast}.`,
  `${host} here on ${podcast}, ready to haunt you with "${episode}".`,
  `Stay spooky with ${host} on ${podcast}, discussing "${episode}".`,
  `${podcast} calls all brave hearts. I’m ${host}, examining "${episode}".`,
  `Beware! ${host} takes on "${episode}" tonight on ${podcast}.`,
  `${host} here with a chilling tale on ${podcast}: "${episode}".`,
  `Welcome to darkness. I’m ${host} on ${podcast}, disclosing "${episode}".`,
  `Fear the truth as ${host} explores "${episode}" on ${podcast}.`,
  `Join ${host} on ${podcast} for a bone-chilling look at "${episode}".`,
  `${podcast} and ${host} bring horror alive with "${episode}".`,
  `Dive into fear with ${host} on ${podcast}, covering "${episode}".`
  ],
   energetic: [
  `Get ready! ${host} here on ${podcast}, hyped to discuss "${episode}".`,
  `Welcome, energy lovers! ${host} on ${podcast} bringing you "${episode}" with a bang!`,
  `Hey everyone! Pumped up ${host} here on ${podcast} for "${episode}".`,
  `Let's go! ${podcast} and ${host} fired up to cover "${episode}".`,
  `Hello, friends! ${host} buzzing with excitement on ${podcast} for "${episode}".`,
  `Ready to boost your day? ${host} here on ${podcast} with "${episode}".`,
  `Welcome back! ${host} bringing energy and insights on "${episode}" for ${podcast}.`,
  `Hey there! It’s your energetic host ${host} on ${podcast} discussing "${episode}".`,
  `Feel the vibe! ${podcast} welcomes ${host} diving into "${episode}".`,
  `Hello everyone! Get excited with ${host} and ${podcast} about "${episode}".`,
  `Let's energize this episode! ${host} here on ${podcast} covering "${episode}".`,
  `Hey friends! ${host} pumped to share thoughts on "${episode}" at ${podcast}.`,
  `Welcome listeners! ${host} ignited and ready on ${podcast} for "${episode}".`,
  `It’s showtime! ${host} here on ${podcast} enthusiastic about "${episode}".`,
  `Feel that buzz? ${host} is live on ${podcast} with "${episode}".`,
  `Hello and energized! ${host} on ${podcast} excited to discuss "${episode}".`,
  `Turn up the volume! ${host} here on ${podcast} talking all about "${episode}".`,
  `Let’s light it up! ${host} on ${podcast} pumped for "${episode}".`,
  `Get hyped! ${host} bringing energy to ${podcast} with "${episode}".`,
  `Welcome energy seekers! ${host} here on ${podcast} for an epic look at "${episode}".`,
  `Hello all! ${host} energized and ready on ${podcast} for "${episode}".`,
  `This is ${host} on ${podcast} bringing the hype all episode long about "${episode}".`,
  `Let’s get energized! ${host} here on ${podcast} with "${episode}".`,
  `Hey folks! ${podcast} and ${host} sparking energy with "${episode}".`,
  `Welcome back! ${host} and ${podcast} ready to energize you with "${episode}".`,
  `Hello listeners! ${host} bringing momentum and insights on "${episode}" at ${podcast}.`,
  `It’s a power hour! ${host} on ${podcast} igniting insights on "${episode}".`,
  `Upbeat and ready! ${host} welcomes you to ${podcast} discussing "${episode}".`,
  `Hello and vibrant! ${host} here on ${podcast} for "${episode}".`,
  `Let’s rock it! ${host} on ${podcast} energizing the talk on "${episode}".`
  ],
   classic: [
   
  ],
  emotional: [
    `Welcome to ${podcast}. I’m ${host}, today’s episode covers "${episode}".`,
  `Good day! ${host} here with ${podcast} discussing "${episode}".`,
  `Greetings! You’re listening to ${podcast} with ${host} on "${episode}".`,
  `Hello everyone! I’m ${host}, and this is ${podcast}, exploring "${episode}".`,
  `Welcome friends! ${host} here to share insights on "${episode}" from ${podcast}.`,
  `Thank you for joining ${podcast}. I’m ${host}, presenting "${episode}".`,
  `Welcome back! This is ${host} on ${podcast} discussing "${episode}".`,
  `Greetings listeners! ${host} here with ${podcast} for a look at "${episode}".`,
  `Hello and welcome! ${host} on ${podcast}, covering the topic "${episode}".`,
  `Good day, friends! ${host} here, ready to talk about "${episode}" on ${podcast}.`,
  `Welcome to another episode of ${podcast}. I’m ${host}, here to inform on "${episode}".`,
  `Greetings! You’re tuned into ${podcast} with ${host}, discussing "${episode}".`,
  `Hello listeners! ${host} here covering "${episode}" on ${podcast}.`,
  `Good day! This is ${host} with ${podcast}, sharing thoughts on "${episode}".`,
  `Welcome, everyone! ${host} here to guide you through "${episode}" on ${podcast}.`,
  `Hello all! ${host} here on ${podcast}, examining "${episode}".`,
  `Good day, folks! ${host} presenting ${podcast} and the episode "${episode}".`,
  `Greetings! ${host} here to detail "${episode}" on ${podcast}.`,
  `Welcome back to ${podcast}. I’m ${host}, providing insight on "${episode}".`,
  `Hello friends! ${host} here to discuss "${episode}" today on ${podcast}.`,
  `Good day! ${host} here with ${podcast}, bringing a classic episode on "${episode}".`,
  `Welcome listeners! ${host} here with ${podcast} discussing "${episode}".`,
  `Hello everyone! ${host} here offering insight on "${episode}" at ${podcast}.`,
  `Good day! This is ${host} on ${podcast}, sharing knowledge about "${episode}".`,
  `Greetings! ${host} presents ${podcast} and today’s episode "${episode}".`,
  `Welcome to ${podcast}, I’m ${host}, discussing the topic "${episode}".`,
  `Hello all! ${host} here on ${podcast}, exploring the nuances of "${episode}".`,
  `Good day, listeners! ${host} here for ${podcast} with "${episode}".`,
  `Welcome back! ${host} with ${podcast}, shedding light on "${episode}".`,
  `Greetings friends! ${host} here discussing "${episode}" on ${podcast}.`,
  `Hello everyone! ${host} on ${podcast} with detailed talk on "${episode}".`
  ],
   };
   const intro = intros[style][Math.floor(Math.random() * intros[style].length)];
  document.getElementById("output").innerText = intro;
}

function generateOutro() {
  const podcast = document.getElementById("podcastName").value;
  const episode = document.getElementById("episodeTitle").value;
  const host = document.getElementById("hostName").value;
  const style = document.getElementById("style").value;
  const outros = {
    professional: [
    `Thanks for listening to ${podcast}. I’m ${host}, see you next time with more insights.`,
  `That wraps up today’s episode on ${podcast}. I’m ${host}, until next time.`,
  `Stay tuned for more discussions on ${podcast}. I’m ${host}.`,
  `We hope you gained valuable knowledge on "${episode}" today. I’m ${host}.`,
  `Thank you for joining ${podcast}. I’m ${host}, see you again soon.`,
  `Thanks for being with us on ${podcast}. I’m ${host}, goodbye for now.`,
  `That concludes another insightful episode of ${podcast}. I’m ${host}.`,
  `We appreciate your time listening to ${podcast}. I’m ${host}.`,
  `Until next time, thanks for tuning in. ${host} here on ${podcast}.`,
  `This ends our talk for today on ${podcast}. I’m ${host}, take care.`,
  `Thanks for joining the discussion on ${podcast}. I’m ${host}, goodbye!`,
  `We hope you found this episode of ${podcast} helpful. I’m ${host}.`,
  `Thanks for listening. ${host} signing off from ${podcast}.`,
  `That’s all for today’s episode on ${podcast}. I’m ${host}, see you soon.`,
  `Goodbye from ${host} on ${podcast}. Thanks for listening!`,
  `Thanks for your time. Join us next time on ${podcast}. I’m ${host}.`,
  `This episode wraps up here. Stay tuned for more on ${podcast} from ${host}.`,
  `Thanks for being with us. I’m ${host} on ${podcast}, until next time.`,
  `Farewell for now. Catch you all soon on ${podcast}. I’m ${host}.`,
  `Thanks for listening! This is ${host} on ${podcast}, signing off.`,
  `We appreciate your time on ${podcast}. I’m ${host}, goodbye!`,
  `Thank you for joining. I’m ${host} on ${podcast}, take care.`,
  `Looking forward to next time. ${host} on ${podcast} signing off.`,
  `That’s a wrap from ${podcast}. Thanks for listening. I’m ${host}.`,
  `Goodbye and take care from ${host} on ${podcast}.`,
  `Thanks for being here. Until next time, I’m ${host} on ${podcast}.`,
  `Farewell friends! Join us again on ${podcast}. I’m ${host}.`,
  `Thanks for your time today on ${podcast}. I’m ${host}, see you soon.`,
  `Thanks for joining us. I’m ${host} on ${podcast}, goodbye for now.`,
  `Until next episode, thanks for tuning in. ${host} on ${podcast}.`
  ],

  humour: [
  `Thanks for tuning in! I’m ${host}, now go make someone laugh!`,
  `That’s a wrap on ${podcast}, hope your day is funnier because of us!`,
  `We hope you enjoyed laughing with us. I’m ${host}.`,
  `Stay humorous! Thanks for listening to ${podcast}, I’m ${host}.`,
  `Catch you next time for more laughs! I’m ${host}.`,
  `Thanks for the laughs today on ${podcast}. I’m ${host}, goodbye!`,
  `Keep smiling until next time from ${host} on ${podcast}.`,
  `That’s a comedic close for ${podcast}. I’m ${host}, see you soon!`,
  `Thanks for the fun! ${host} signing off from ${podcast}.`,
  `Stay laughing, friends! I’m ${host} on ${podcast}, goodbye!`,
  `Thanks for the smiles. Catch you next time on ${podcast} with ${host}.`,
  `Keep the humour alive. I’m ${host} on ${podcast}, farewell!`,
  `Laugh with us again soon. This is ${host} on ${podcast}, goodbye!`,
  `Thanks for jokes and joy on ${podcast}. I’m ${host}, signing off.`,
  `That’s all for laughs today. See you next time on ${podcast}.`,
  `Smile on! ${host} on ${podcast} signing off with thanks.`,
  `Thanks for sharing the laughs. Until next time, ${host} on ${podcast}.`,
  `Keep your spirits high! ${host} here on ${podcast} signing off.`,
  `Thanks for the chuckles on ${podcast}. I’m ${host}, goodbye!`,
  `See you next time with laughs. This is ${host} on ${podcast}.`,
  `Keep it light and funny! ${host} signing off from ${podcast}.`,
  `Thanks for giggles and grins. Goodbye from ${host} on ${podcast}.`,
  `Catch the next episode with more laughs. I’m ${host} on ${podcast}.`,
  `Thanks for the fun company! ${host} on ${podcast} saying goodbye.`,
  `Laugh on! This is ${host} signing off ${podcast}.`,
  `Thanks for the joyride on ${podcast}. I’m ${host}, see you again!`,
  `Stay silly and smile! ${host} on ${podcast} signing off now.`,
  `Thanks for tuning into the fun. I’m ${host} on ${podcast}, goodbye!`,
  `Keep laughing! Thanks from ${host} on ${podcast}.`,
  `That’s it for today’s laughs. Catch you next time on ${podcast}.`,
  `Goodbye from ${host} on ${podcast}. Keep the humour alive!`
  ],

  satire: [
    `That’s all for today’s satirical take. I’m ${host}.`,
  `Thanks for joining, where irony meets insight. I’m ${host}.`,
  `We hope you enjoyed the satire. I’m ${host}.`,
  `Stay witty! Thanks for listening, I’m ${host}.`,
  `Catch the next satirical episode. I’m ${host}.`,
  `Thanks for the irony and laughs on ${podcast}. I’m ${host}, goodbye!`,
  `That wraps up this satirical episode. See you next time on ${podcast}.`,
  `Stay sharp and clever! ${host} signing off from ${podcast}.`,
  `Thanks for the witty company. I’m ${host} on ${podcast}, farewell!`,
  `Keep the satire alive! ${host} here on ${podcast}, goodbye!`,
  `Thanks for the laughs and insights. I’m ${host} on ${podcast}, see you soon!`,
  `Enjoyed the satire? Join us again on ${podcast}. I’m ${host}.`,
  `That’s all for now, folks! ${host} on ${podcast} signing off.`,
  `Thanks for the cleverness! Farewell from ${host} and ${podcast}.`,
  `Stay ironic till next time! ${host} on ${podcast} goodbye.`,
  `Thanks for an insightful satire episode. I’m ${host}, see you next time!`,
  `Keep your wit sharp! ${host} on ${podcast} signing out.`,
  `Thanks for listening with a smile. I’m ${host} on ${podcast}, goodbye!`,
  `Catch you next time for more satire. This is ${host} on ${podcast}.`,
  `Farewell from ${host} on ${podcast}. Keep enjoying the satire!`,
  `Thanks for joining the satire ride. ${host} on ${podcast} signing off.`,
  `Stay clever and watchful! I’m ${host} on ${podcast}, goodbye.`,
  `That concludes this satirical episode. Thanks for listening!`,
  `Thanks for joining us in wit and humor. ${host} on ${podcast} signing off.`,
  `Goodbye for now! ${host} here on ${podcast} with more satire soon.`,
  `Thanks for your wit and company. ${host} on ${podcast} says farewell.`,
  `That’s a wrap from ${podcast}. See you next time with more satire!`,
  `Stay witty! Thanks from ${host} on ${podcast}.`,
  `Thanks for the smart laughs. I’m ${host} signing off ${podcast}.`,
  `Enjoy the irony until next time. ${host} here on ${podcast}, goodbye!`,
  `Thanks for the satire today! I’m ${host} on ${podcast}, take care.`
  ],

  horror: [
   `Thanks for joining us in the darkness on ${podcast}. I’m ${host}, until next time.`,
  `That’s a wrap on our chilling journey of ${episode}. Stay safe, ${host} here.`,
  `The shadows fade for now, but ${podcast} returns. I’m ${host}.`,
  `Thanks for braving the horror with us on ${podcast}. I’m ${host}.`,
  `Keep your lights on until next time from ${podcast}. I’m ${host}.`,
  `This concludes the nightmare. Until next time, ${host} on ${podcast}.`,
  `May your nights be safe. ${host} signing off from ${podcast}.`,
  `The terror is paused. Join us again on ${podcast}, I’m ${host}.`,
  `Farewell from the darkness. ${host} out, see you on ${podcast}.`,
  `Thanks for surviving ${episode} with us on ${podcast}. I’m ${host}.`,
  `The haunt ends for now. Catch you next time on ${podcast}.`,
  `Until then, keep vigilant. ${host} on ${podcast} signing off.`,
  `Darkness retreats for now. Goodbye from ${host} on ${podcast}.`,
  `Thanks for sticking with us through the fear on ${podcast}, ${host} here.`,
  `Our eerie tales pause here. Stay safe until next time, I’m ${host}.`,
  `Fear not, ${podcast} will return. ${host} signing off.`,
  `Thanks for the bravery tonight on ${podcast}. I’m ${host}, take care.`,
  `Until the next shadow falls, farewell from ${podcast} and ${host}.`,
  `The nightmare ends. Join us again soon, this is ${host} on ${podcast}.`,
  `Goodbye for now from the darkness of ${podcast}. I’m ${host}.`,
  `The night is over, but the story continues on ${podcast}. I’m ${host}.`,
  `Thanks for tuning into the terror. Until next time, ${host} here.`,
  `The horror stops here, but stay tuned for more. ${host} from ${podcast}.`,
  `Leaving you with chills, this is ${host} on ${podcast}.`,
  `Dark stories await in the future. Farewell from ${host} and ${podcast}.`,
  `Thanks for joining the fright night. I’m ${host}, signing off ${podcast}.`,
  `Our scary tale ends. See you next episode on ${podcast}, ${host} here.`,
  `Keep your fears close. Goodbye from ${host} on ${podcast}.`,
  `Until the next scare, thanks for listening. ${host} on ${podcast}.`,
  `The darkness is gone for now. Farewell from ${host} and ${podcast}.`
  ],

  energetic: [
    `Thanks for the energy boost with ${podcast}. I’m ${host}, see you next time!`,
  `That’s a wrap on this energized episode. Stay hyped! ${host} here on ${podcast}.`,
  `Keep your energy high till next time. Thanks from ${host} on ${podcast}.`,
  `Thanks for tuning in! This is ${host} keeping the momentum on ${podcast}.`,
  `Stay energized! ${host} signing off from ${podcast}.`,
  `What a ride! Thanks for joining ${podcast}, I’m ${host}.`,
  `Keep that spark alive! Until next time, ${host} on ${podcast}.`,
  `Thanks for bringing your energy here. ${host} on ${podcast}, see you soon!`,
  `Stay upbeat and positive. This is ${host} from ${podcast} saying goodbye!`,
  `That ends this energized session. Catch you next time from ${host} and ${podcast}.`,
  `Thanks for the vibe! ${host} closing out ${podcast} for now.`,
  `Keep the energy flowing until our next episode. ${host} on ${podcast}.`,
  `Be well and energized! This is ${host} on ${podcast}.`,
  `Thanks for the motivation today! ${host} signing off from ${podcast}.`,
  `Catch you next time with more energy. ${host} here on ${podcast}.`,
  `Stay charged! Thanks for listening to ${podcast}, ${host} here.`,
  `Keep moving forward with energy! ${host} on ${podcast} signing off.`,
  `Thanks for the boost! See you again from ${host} and ${podcast}.`,
  `Stay motivated! This is ${host} wrapping up ${podcast}.`,
  `Thanks for the great energy today. Bye from ${host} on ${podcast}.`,
  `Keep that enthusiasm alive! ${host} here on ${podcast} signing off.`,
  `Thanks for joining the energy wave. Until next time, ${host} on ${podcast}.`,
  `That’s a wrap! Stay pumped, ${host} here on ${podcast}.`,
  `Thanks for the hype! This is ${host} on ${podcast}.`,
  `Keep the fire burning. ${host} saying goodbye from ${podcast}.`,
  `Stay energized as always! ${host} on ${podcast} signing out.`,
  `Thanks for your energy and time today! Goodbye from ${host} and ${podcast}.`,
  `Keep pushing forward. ${host} out from ${podcast}.`,
  `Thanks for an electrifying episode! See you next time on ${podcast}.`,
  `Energy up! This is ${host} on ${podcast}, signing off.`
  ],

  classic: [
  `Thanks for listening to ${podcast}. I’m ${host}, see you next time.`,
  `That concludes this episode of ${podcast}. I’m ${host}, goodbye for now.`,
  `Thank you for joining ${podcast}. I’m ${host}. Until next time!`,
  `We hope you enjoyed ${episode} today on ${podcast}. I’m ${host}.`,
  `Goodbye from ${host} on ${podcast}. Looking forward to next episode.`,
  `Thanks for your time today on ${podcast}. I’m ${host}.`,
  `That wraps up another classic episode of ${podcast}. I’m ${host}.`,
  `Farewell until next time from ${host} and ${podcast}.`,
  `Thanks for joining us on ${podcast}. I’m ${host}, goodbye!`,
  `We appreciate your company on ${podcast}. I’m ${host}.`,
  `Goodbye for now from ${podcast}. I’m ${host}, stay safe.`,
  `That’s all for today, thanks for listening! I’m ${host} on ${podcast}.`,
  `Thanks for spending time with ${podcast}. I’m ${host}, take care.`,
  `Farewell friends! Until the next episode of ${podcast}. I’m ${host}.`,
  `Thank you for being with us today on ${podcast}. I’m ${host}.`,
  `See you next time on ${podcast}. Goodbye from ${host}.`,
  `Thanks for tuning in! This is ${host} from ${podcast}.`,
  `See you next time on ${podcast}. Goodbye from ${host}.`,
  `Thanks for tuning in! This is ${host} from ${podcast}.`,
  `Goodbye and take care! From ${host} on ${podcast}.`,
  `Thanks for listening! I’m ${host}, see you again on ${podcast}.`,
  `Until next time, thanks for being here. ${host} on ${podcast}.`,
  `That ends our classic episode for ${podcast}. I’m ${host}.`,
  `Thanks for your company on ${podcast}! I’m ${host}.`,
  `Farewell until next episode from ${host} and ${podcast}.`,
  `We’ll see you again soon on ${podcast}. Signed, ${host}.`,
  `Thanks for joining the conversation on ${podcast}. I’m ${host}.`,
  `Goodbye for now from ${host} on ${podcast}.`,
  `Thank you for your time on ${podcast}. I’m ${host}.`,
  `That’s all today on ${podcast}. I’m ${host}, take care.`,
  `Farewell and thanks from ${host} on ${podcast}.`,
  `Goodbye friends! See you on the next ${podcast} episode!`
  ],

  emotional: [
  `Thank you for sharing your heart with us on ${podcast}. I’m ${host}.`,
  `That’s all for today’s heartfelt episode. Until next time, I’m ${host}.`,
  `We hope you felt the emotions in ${episode} today. This is ${host} signing off.`,
  `Thanks for joining us on this emotional journey on ${podcast}. I’m ${host}.`,
  `Farewell until next time from ${host} on ${podcast}. Stay kind.`,
  `Thank you for being here and feeling with us. I’m ${host} on ${podcast}.`,
  `That’s the end of this touching episode. I’m ${host}, take care.`,
  `We hope this touched your heart. Goodbye from ${host} on ${podcast}.`,
  `Thanks for letting us into your emotions on ${podcast}. I’m ${host}.`,
  `Stay heartfelt and warm until next time. ${host} here on ${podcast}.`,
  `Thanks for listening with your heart. This is ${host} on ${podcast}, goodbye.`,
  `Farewell from ${host} and ${podcast}. Keep your heart open.`,
  `Thank you for sharing this moment on ${podcast}. I’m ${host}.`,
  `Goodbye for now! Stay emotional and kind. ${host} on ${podcast}.`,
  `That wraps up this episode on ${podcast}. I’m ${host}, stay well.`,
  `Thank you for joining ${podcast} today. I’m ${host}, take care until next time.`,
  `Thanks for listening and feeling with us. Bye from ${host} on ${podcast}.`,
  `Farewell and keep the love alive. I’m ${host} on ${podcast}.`,
  `Thanks for being part of this emotional episode. I’m ${host}.`,
  `Until next time, keep your heart open. Goodbye from ${host} on ${podcast}.`,
  `That’s all for today’s journey of the heart. ${host} here on ${podcast}.`,
  `Thank you for listening to ${podcast}. I’m ${host}, take care.`,
  `Farewell until next time from your friend ${host} on ${podcast}.`,
  `Thanks for spending this time with us. I’m ${host} signing off ${podcast}.`,
  `Stay kind and emotional till we meet again. ${host} on ${podcast}.`,
  `Thank you for tuning in. ${host} from ${podcast} says goodbye.`,
  `Goodbye for now! Keep your feelings close. ${host} on ${podcast}.`,
  `Thanks for joining the emotional experience on ${podcast}. ${host} here.`,
  `Farewell friends! Until next episode on ${podcast}. I’m ${host}.`
  ]
  };

  // randomly pick one outro
  const outro = outros[style][Math.floor(Math.random() * outros[style].length)];
  document.getElementById("output").innerText = outro;
}
